### ISSUE TITLE
Join / participate to an event  event.blockingParticipate()

### ISSUE THREAD

**Issue by tigran-e-works** [MySocialApp/mysocialapp-java-client#1]
Hi.

 I want to join to event using this method "event.participate()" ,but it always get me HTTP  error 400 and I can't see error message. Can You please show me good example how can I join to event and catch success or failure callbacks?

 Thank You!

**Comment by evoxmusic** [comment]
@tigran-e-works How you can handle errors https://github.com/MySocialApp/mysocialapp-java-client#handle-exceptions

**Comment by evoxmusic** [comment]
@tigran-e-works can you provide me the exact code that you do to reproduce it?

**Comment by evoxmusic** [comment]
@tigran-e-works can you try with the last version?

**Comment by evoxmusic** [comment]
No news? Seems to be good for you. I close. Cheers
