### ISSUE TITLE
Event -> User object -> isFriend values

### ISSUE THREAD

**Issue by davittorosyan** [MySocialApp/mysocialapp-java-client#5]
**Describe the bug**
in Event -> user object -> isFriend is alwasy nullm can you please add boolen values for this?

Also, can you please fix memberItem.getUser().requestAsFriend() method? After running this method is always onComplete(), there are no any true/false response.

**Comment by evoxmusic** [comment]
Hey @davittorosyan ,

> in Event -> user object -> isFriend is alwasy nullm can you please add boolen values for this?

This will be available through `.setLimited(false)` method. 

> Also, can you please fix memberItem.getUser().requestAsFriend() method? After running this method is always onComplete(), there are no any true/false response.

Please open another issue for this. But not sure that it will be added very soon

**Comment by evoxmusic** [comment]
Done

**Comment by davittorosyan** [comment]
@evoxmusic unfortunately we again have nil there 
our request
![b56a895fd8240cdac1b8debf693d2f737734d15f3236881661 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/25083334/42525698-e3899a3c-8484-11e8-99c2-94857820ed23.png)


your response
![capture3](https://user-images.githubusercontent.com/25083334/42525762-0abdba7a-8485-11e8-9298-a733a2ce63ee.PNG)


sdk version 
0.9.0

**Comment by evoxmusic** [comment]
Hey @davittorosyan ,

Fixed, please use v0.10.0
