### ISSUE TITLE
User search by externalID

### ISSUE THREAD

**Issue by davittorosyan** [MySocialApp/mysocialapp-java-client#6]
**Describe the bug**
Can you please add user search by externalID?

```
FluentUser.Search query = new FluentUser.Search.Builder()
.setFirstName(memberItem.getUser().getFirstName())
.build();
```

**Comment by evoxmusic** [comment]
We have to planned this for a next release. We have to make major change to support this. Is it something blocking?

**Comment by davittorosyan** [comment]
@evoxmusic yes, we need this, because currently we find user by name which is not good, because can be different users with same name.. we need find user by ID

**Comment by evoxmusic** [comment]
Did you see that you can get user by external ID ? https://github.com/MySocialApp/mysocialapp-java-client#how-to-integrate-a-mysocialapp-user-with-an-existing-user-in-my-application
