### ISSUE TITLE
memberItem.getUser().requestAsFriend() response

### ISSUE THREAD

**Issue by davittorosyan** [MySocialApp/mysocialapp-java-client#7]
**Describe the bug**
Can you please fix memberItem.getUser().requestAsFriend() method? After running this method is always onComplete(), there are no any true/false response.

**Comment by evoxmusic** [comment]
Hey @davittorosyan , there is nothing to fix here. The behaviour is completely wanted.
Whether the user is already friend or not, the response will be the same. You should consider the action done by the user client side.
