### ISSUE TITLE
Subscriber Count when unParticipate 

### ISSUE THREAD

**Issue by davittorosyan** [MySocialApp/mysocialapp-java-client#8]
**Describe the bug**
Can you please check unparticipate function returned result?
looks like the participants count is not updated, but this is looks good for "participate" function returned result
![capture](https://user-images.githubusercontent.com/25083334/42748596-cf0b6ede-88f1-11e8-961f-526b384f2230.PNG)

**Environment**
* Runtime version: 0.10.0

**Comment by evoxmusic** [comment]
This has been corrected, it will be completely fixed and deployed in one hour.
