### ISSUE TITLE
Filter result is null

### ISSUE THREAD

**Issue by davittorosyan** [MySocialApp/mysocialapp-java-client#9]
**Describe the bug**
Can you please check screenshots, what is wrong in our parameters?
We always receiving null

request
![screenshot1](https://user-images.githubusercontent.com/25083334/42829691-1c63951c-89fb-11e8-8206-319d5af0ba20.PNG)

response
![screenshot2](https://user-images.githubusercontent.com/25083334/42829702-228ec876-89fb-11e8-8ea8-d3d7123bf09c.PNG)

**Environment**
0.10.0

**Comment by evoxmusic** [comment]
Hey @davittorosyan , I am going to release a new version today or tomorrow.

**Comment by evoxmusic** [comment]
@davittorosyan can you please try it again with the v0.12.0 release
